SWCONFIG_VERSION = 12
SWCONFIG_LICENSE = GPL-2.0
SWCONFIG_SITE = $(SWCONFIG_PKGDIR)/src
SWCONFIG_SITE_METHOD = local

SWCONFIG_DEPENDENCIES += libnl libubox

define SWCONFIG_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) CC="$(TARGET_CC)" ALLFLAGS_C="$(TARGET_CFLAGS)" \
		CXX="$(TARGET_CXX)" ALLFLAGS_CPP="$(TARGET_CXXFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS)" \
		-C $(@D)
endef

define SWCONFIG_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/swconfig $(TARGET_DIR)/bin
endef

$(eval $(generic-package))
